INSERT INTO mydb.estado (idEstado, sigla) VALUES (1, 'PR');
INSERT INTO mydb.estado (idEstado, sigla) VALUES (2, 'SC');
INSERT INTO mydb.estado (idEstado, sigla) VALUES (3, 'RS');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Abatiá');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Adrianópolis');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Agudos do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Almirante Tamandaré');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Altamira do Paraná');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Alto Paraíso');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Alto Paraná');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Alto Piquiri');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Altônia');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Alvorada do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Amaporã');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Ampére');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Anahy');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Andirá');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Ângulo');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Antonina');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Antônio Olinto');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Apucarana');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Arapongas');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Arapoti');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Arapuã');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Araruna');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Araucária');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Ariranha do Ivaí');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Assaí');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Assis Chateaubriand');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Astorga');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Atalaia');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Balsa Nova');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Bandeirantes');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Barbosa Ferraz');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Barra do Jacaré');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Barracão');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Bela Vista da Caroba');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Bela Vista do Paraíso');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Bituruna');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Boa Esperança');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Boa Esperança do Iguaçu');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Boa Ventura de São Roque');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Boa Vista da Aparecida');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Bocaiúva do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Bom Jesus do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Bom Sucesso');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Bom Sucesso do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Borrazópolis');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Braganey');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Brasilândia do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Cafeara');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Cafelândia');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Cafezal do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Califórnia');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Cambará');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Cambé');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Cambira');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Campina da Lagoa');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Campina do Simão');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Campina Grande do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Campo Bonito');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Campo do Tenente');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Campo Largo');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Campo Magro');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Campo Mourão');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Cândido de Abreu');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Candói');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Cantagalo');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Capanema');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Capitão Leônidas Marques');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Carambeí');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Carlópolis');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Cascavel');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Castro');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Catanduvas');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Centenário do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Cerro Azul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Céu Azul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Chopinzinho');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Cianorte');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Cidade Gaúcha');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Clevelândia');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Colombo');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Colorado');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Congonhinhas');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Conselheiro Mairinck');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Contenda');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Corbélia');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Cornélio Procópio');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Coronel Domingos Soares');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Coronel Vivida');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Corumbataí do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Cruz Machado');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Cruzeiro do Iguaçu');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Cruzeiro do Oeste');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Cruzeiro do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Cruzmaltina');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Curitiba');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Curiúva');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Diamante do Norte');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Diamante do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Diamante Doeste');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Dois Vizinhos');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Douradina');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Doutor Camargo');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Doutor Ulysses');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Enéas Marques');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Engenheiro Beltrão');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Entre Rios do Oeste');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Esperança Nova');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Espigão Alto do Iguaçu');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Farol');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Faxinal');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Fazenda Rio Grande');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Fênix');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Fernandes Pinheiro');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Figueira');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Flor da Serra do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Floraí');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Floresta');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Florestópolis');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Flórida');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Formosa do Oeste');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Foz do Iguaçu');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Foz do Jordão');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Francisco Alves');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Francisco Beltrão');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'General Carneiro');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Godoy Moreira');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Goioerê');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Goioxim');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Grandes Rios');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Guaíra');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Guairaçá');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Guamiranga');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Guapirama');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Guaporema');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Guaraci');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Guaraniaçu');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Guarapuava');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Guaraqueçaba');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Guaratuba');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Honório Serpa');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Ibaiti');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Ibema');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Ibiporã');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Icaraíma');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Iguaraçu');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Iguatu');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Imbaú');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Imbituva');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Inácio Martins');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Inajá');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Indianópolis');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Ipiranga');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Iporã');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Iracema do Oeste');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Irati');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Iretama');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Itaguajé');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Itaipulândia');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Itambaracá');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Itambé');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Itapejara Doeste');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Itaperuçu');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Itaúna do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Ivaí');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Ivaiporã');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Ivaté');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Ivatuba');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Jaboti');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Jacarezinho');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Jaguapitã');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Jaguariaíva');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Jandaia do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Janiópolis');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Japira');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Japurá');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Jardim Alegre');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Jardim Olinda');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Jataizinho');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Jesuítas');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Joaquim Távora');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Jundiaí do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Juranda');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Jussara');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Kaloré');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Lapa');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Laranjal');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Laranjeiras do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Leópolis');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Lidianópolis');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Lindoeste');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Loanda');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Lobato');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Londrina');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Luiziana');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Lunardelli');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Lupionópolis');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Mallet');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Mamborê');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Mandaguaçu');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Mandaguari');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Mandirituba');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Manfrinópolis');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Mangueirinha');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Manoel Ribas');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Marechal Cândido Rondon');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Maria Helena');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Marialva');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Marilândia do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Marilena');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Mariluz');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Maringá');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Mariópolis');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Maripá');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Marmeleiro');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Marquinho');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Marumbi');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Matelândia');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Matinhos');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Mato Rico');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Mauá da Serra');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Medianeira');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Mercedes');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Mirador');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Miraselva');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Missal');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Moreira Sales');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Morretes');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Munhoz de Melo');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Nossa Senhora das Graças');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Nova Aliança do Ivaí');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Nova América da Colina');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Nova Aurora');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Nova Cantu');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Nova Esperança');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Nova Esperança do Sudoeste');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Nova Fátima');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Nova Laranjeiras');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Nova Londrina');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Nova Olímpia');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Nova Prata do Iguaçu');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Nova Santa Bárbara');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Nova Santa Rosa');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Nova Tebas');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Novo Itacolomi');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Ortigueira');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Ourizona');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Ouro Verde do Oeste');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Paiçandu');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Palmas');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Palmeira');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Palmital');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Palotina');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Paraíso do Norte');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Paranacity');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Paranaguá');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Paranapoema');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Paranavaí');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Pato Bragado');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Pato Branco');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Paula Freitas');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Paulo Frontin');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Peabiru');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Perobal');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Pérola');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Pérola Doeste');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Piên');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Pinhais');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Pinhal de São Bento');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Pinhalão');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Pinhão');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Piraí do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Piraquara');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Pitanga');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Pitangueiras');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Planaltina do Paraná');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Planalto');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Ponta Grossa');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Pontal do Paraná');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Porecatu');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Porto Amazonas');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Porto Barreiro');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Porto Rico');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Porto Vitória');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Prado Ferreira');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Pranchita');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Presidente Castelo Branco');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Primeiro de Maio');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Prudentópolis');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Quarto Centenário');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Quatiguá');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Quatro Barras');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Quatro Pontes');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Quedas do Iguaçu');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Querência do Norte');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Quinta do Sol');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Quitandinha');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Ramilândia');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Rancho Alegre');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Rancho Alegre Doeste');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Realeza');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Rebouças');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Renascença');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Reserva');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Reserva do Iguaçu');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Ribeirão Claro');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Ribeirão do Pinhal');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Rio Azul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Rio Bom');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Rio Bonito do Iguaçu');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Rio Branco do Ivaí');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Rio Branco do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Rio Negro');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Rolândia');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Roncador');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Rondon');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Rosário do Ivaí');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Sabáudia');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Salgado Filho');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Salto do Itararé');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Salto do Lontra');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Santa Amélia');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Santa Cecília do Pavão');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Santa Cruz de Monte Castelo');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Santa Fé');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Santa Helena');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Santa Inês');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Santa Isabel do Ivaí');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Santa Izabel do Oeste');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Santa Lúcia');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Santa Maria do Oeste');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Santa Mariana');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Santa Mônica');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Santa Tereza do Oeste');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Santa Terezinha de Itaipu');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Santana do Itararé');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Santo Antônio da Platina');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Santo Antônio do Caiuá');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Santo Antônio do Paraíso');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Santo Antônio do Sudoeste');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Santo Inácio');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'São Carlos do Ivaí');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'São Jerônimo da Serra');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'São João');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'São João do Caiuá');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'São João do Ivaí');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'São João do Triunfo');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'São Jorge do Ivaí');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'São Jorge do Patrocínio');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'São Jorge Doeste');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'São José da Boa Vista');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'São José das Palmeiras');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'São José dos Pinhais');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'São Manoel do Paraná');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'São Mateus do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'São Miguel do Iguaçu');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'São Pedro do Iguaçu');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'São Pedro do Ivaí');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'São Pedro do Paraná');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'São Sebastião da Amoreira');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'São Tomé');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Sapopema');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Sarandi');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Saudade do Iguaçu');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Sengés');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Serranópolis do Iguaçu');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Sertaneja');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Sertanópolis');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Siqueira Campos');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Sulina');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Tamarana');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Tamboara');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Tapejara');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Tapira');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Teixeira Soares');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Telêmaco Borba');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Terra Boa');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Terra Rica');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Terra Roxa');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Tibagi');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Tijucas do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Toledo');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Tomazina');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Três Barras do Paraná');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Tunas do Paraná');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Tuneiras do Oeste');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Tupãssi');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Turvo');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Ubiratã');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Umuarama');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'União da Vitória');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Uniflor');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Uraí');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Ventania');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Vera Cruz do Oeste');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Verê');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Virmond');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Vitorino');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Wenceslau Braz');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (1,'Xambrê');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Abdon Batista');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Abelardo Luz');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Agrolândia');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Agronômica');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Água Doce');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Águas de Chapecó');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Águas Frias');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Águas Mornas');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Alfredo Wagner');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Alto Bela Vista');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Anchieta');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Angelina');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Anita Garibaldi');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Anitápolis');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Antônio Carlos');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Apiúna');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Arabutã');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Araquari');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Araranguá');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Armazém');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Arroio Trinta');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Arvoredo');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Ascurra');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Atalanta');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Aurora');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Balneário Arroio do Silva');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Balneário Barra do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Balneário Camboriú');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Balneário Gaivota');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Balneário Piçarras');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Bandeirante');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Barra Bonita');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Barra Velha');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Bela Vista do Toldo');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Belmonte');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Benedito Novo');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Biguaçu');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Blumenau');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Bocaina do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Bom Jardim da Serra');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Bom Jesus');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Bom Jesus do Oeste');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Bom Retiro');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Bombinhas');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Botuverá');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Braço do Norte');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Braço do Trombudo');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Brunópolis');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Brusque');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Caçador');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Caibi');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Calmon');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Camboriú');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Campo Alegre');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Campo Belo do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Campo Erê');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Campos Novos');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Canelinha');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Canoinhas');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Capão Alto');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Capinzal');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Capivari de Baixo');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Catanduvas');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Caxambu do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Celso Ramos');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Cerro Negro');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Chapadão do Lageado');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Chapecó');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Cocal do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Concórdia');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Cordilheira Alta');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Coronel Freitas');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Coronel Martins');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Correia Pinto');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Corupá');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Criciúma');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Cunha Porã');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Cunhataí');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Curitibanos');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Descanso');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Dionísio Cerqueira');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Dona Emma');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Doutor Pedrinho');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Entre Rios');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Ermo');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Erval Velho');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Faxinal dos Guedes');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Flor do Sertão');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Florianópolis');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Formosa do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Forquilhinha');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Fraiburgo');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Frei Rogério');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Galvão');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Garopaba');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Garuva');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Gaspar');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Governador Celso Ramos');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Grão Pará');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Gravatal');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Guabiruba');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Guaraciaba');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Guaramirim');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Guarujá do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Guatambú');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Herval Doeste');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Ibiam');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Ibicaré');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Ibirama');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Içara');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Ilhota');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Imaruí');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Imbituba');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Imbuia');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Indaial');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Iomerê');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Ipira');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Iporã do Oeste');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Ipuaçu');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Ipumirim');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Iraceminha');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Irani');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Irati');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Irineópolis');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Itá');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Itaiópolis');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Itajaí');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Itapema');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Itapiranga');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Itapoá');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Ituporanga');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Jaborá');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Jacinto Machado');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Jaguaruna');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Jaraguá do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Jardinópolis');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Joaçaba');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Joinville');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'José Boiteux');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Jupiá');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Lacerdópolis');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Lages');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Laguna');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Lajeado Grande');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Laurentino');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Lauro Muller');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Lebon Régis');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Leoberto Leal');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Lindóia do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Lontras');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Luiz Alves');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Luzerna');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Macieira');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Mafra');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Major Gercino');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Major Vieira');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Maracajá');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Maravilha');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Marema');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Massaranduba');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Matos Costa');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Meleiro');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Mirim Doce');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Modelo');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Mondaí');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Monte Carlo');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Monte Castelo');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Morro da Fumaça');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Morro Grande');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Navegantes');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Nova Erechim');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Nova Itaberaba');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Nova Trento');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Nova Veneza');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Novo Horizonte');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Orleans');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Otacílio Costa');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Ouro');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Ouro Verde');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Paial');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Painel');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Palhoça');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Palma Sola');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Palmeira');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Palmitos');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Papanduva');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Paraíso');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Passo de Torres');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Passos Maia');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Paulo Lopes');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Pedras Grandes');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Penha');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Peritiba');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Petrolândia');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Pinhalzinho');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Pinheiro Preto');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Piratuba');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Planalto Alegre');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Pomerode');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Ponte Alta');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Ponte Alta do Norte');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Ponte Serrada');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Porto Belo');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Porto União');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Pouso Redondo');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Praia Grande');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Presidente Castello Branco');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Presidente Getúlio');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Presidente Nereu');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Princesa');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Quilombo');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Rancho Queimado');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Rio das Antas');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Rio do Campo');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Rio do Oeste');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Rio do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Rio dos Cedros');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Rio Fortuna');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Rio Negrinho');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Rio Rufino');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Riqueza');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Rodeio');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Romelândia');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Salete');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Saltinho');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Salto Veloso');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Sangão');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Santa Cecília');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Santa Helena');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Santa Rosa de Lima');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Santa Rosa do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Santa Terezinha');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Santa Terezinha do Progresso');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Santiago do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Santo Amaro da Imperatriz');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'São Bento do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'São Bernardino');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'São Bonifácio');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'São Carlos');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'São Cristovão do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'São Domingos');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'São Francisco do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'São João Batista');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'São João do Itaperiú');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'São João do Oeste');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'São João do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'São Joaquim');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'São José');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'São José do Cedro');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'São José do Cerrito');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'São Lourenço do Oeste');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'São Ludgero');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'São Martinho');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'São Miguel da Boa Vista');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'São Miguel do Oeste');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'São Pedro de Alcântara');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Saudades');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Schroeder');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Seara');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Serra Alta');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Siderópolis');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Sombrio');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Sul Brasil');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Taió');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Tangará');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Tigrinhos');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Tijucas');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Timbé do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Timbó');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Timbó Grande');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Três Barras');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Treviso');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Treze de Maio');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Treze Tílias');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Trombudo Central');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Tubarão');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Tunápolis');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Turvo');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'União do Oeste');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Urubici');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Urupema');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Urussanga');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Vargeão');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Vargem');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Vargem Bonita');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Vidal Ramos');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Videira');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Vitor Meireles');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Witmarsum');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Xanxerê');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Xavantina');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Xaxim');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (2,'Zortéa');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Aceguá');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Água Santa');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Agudo');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Ajuricaba');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Alecrim');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Alegrete');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Alegria');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Almirante Tamandaré do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Alpestre');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Alto Alegre');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Alto Feliz');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Alvorada');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Amaral Ferrador');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Ametista do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'André da Rocha');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Anta Gorda');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Antônio Prado');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Arambaré');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Araricá');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Aratiba');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Arroio do Meio');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Arroio do Padre');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Arroio do Sal');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Arroio do Tigre');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Arroio dos Ratos');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Arroio Grande');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Arvorezinha');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Augusto Pestana');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Áurea');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Bagé');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Balneário Pinhal');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Barão');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Barão de Cotegipe');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Barão do Triunfo');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Barra do Guarita');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Barra do Quaraí');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Barra do Ribeiro');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Barra do Rio Azul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Barra Funda');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Barracão');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Barros Cassal');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Benjamin Constant do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Bento Gonçalves');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Boa Vista das Missões');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Boa Vista do Buricá');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Boa Vista do Cadeado');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Boa Vista do Incra');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Boa Vista do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Bom Jesus');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Bom Princípio');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Bom Progresso');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Bom Retiro do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Boqueirão do Leão');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Bossoroca');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Bozano');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Braga');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Brochier');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Butiá');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Caçapava do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Cacequi');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Cachoeira do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Cachoeirinha');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Cacique Doble');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Caibaté');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Caiçara');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Camaquã');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Camargo');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Cambará do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Campestre da Serra');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Campina das Missões');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Campinas do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Campo Bom');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Campo Novo');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Campos Borges');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Candelária');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Cândido Godói');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Candiota');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Canela');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Canguçu');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Canoas');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Canudos do Vale');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Capão Bonito do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Capão da Canoa');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Capão do Cipó');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Capão do Leão');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Capela de Santana');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Capitão');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Capivari do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Caraá');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Carazinho');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Carlos Barbosa');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Carlos Gomes');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Casca');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Caseiros');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Catuípe');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Caxias do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Centenário');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Cerrito');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Cerro Branco');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Cerro Grande');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Cerro Grande do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Cerro Largo');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Chapada');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Charqueadas');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Charrua');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Chiapetta');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Chuí');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Chuvisca');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Cidreira');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Ciríaco');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Colinas');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Colorado');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Condor');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Constantina');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Coqueiro Baixo');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Coqueiros do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Coronel Barros');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Coronel Bicaco');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Coronel Pilar');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Cotiporã');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Coxilha');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Crissiumal');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Cristal');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Cristal do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Cruz Alta');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Cruzaltense');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Cruzeiro do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'David Canabarro');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Derrubadas');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Dezesseis de Novembro');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Dilermando de Aguiar');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Dois Irmãos');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Dois Irmãos das Missões');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Dois Lajeados');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Dom Feliciano');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Dom Pedrito');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Dom Pedro de Alcântara');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Dona Francisca');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Doutor Maurício Cardoso');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Doutor Ricardo');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Eldorado do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Encantado');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Encruzilhada do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Engenho Velho');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Entre Rios do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Entre-Ijuís');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Erebango');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Erechim');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Ernestina');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Erval Grande');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Erval Seco');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Esmeralda');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Esperança do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Espumoso');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Estação');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Estância Velha');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Esteio');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Estrela');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Estrela Velha');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Eugênio de Castro');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Fagundes Varela');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Farroupilha');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Faxinal do Soturno');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Faxinalzinho');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Fazenda Vilanova');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Feliz');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Flores da Cunha');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Floriano Peixoto');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Fontoura Xavier');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Formigueiro');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Forquetinha');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Fortaleza dos Valos');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Frederico Westphalen');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Garibaldi');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Garruchos');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Gaurama');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'General Câmara');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Gentil');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Getúlio Vargas');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Giruá');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Glorinha');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Gramado');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Gramado dos Loureiros');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Gramado Xavier');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Gravataí');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Guabiju');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Guaíba');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Guaporé');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Guarani das Missões');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Harmonia');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Herval');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Herveiras');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Horizontina');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Hulha Negra');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Humaitá');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Ibarama');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Ibiaçá');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Ibiraiaras');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Ibirapuitã');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Ibirubá');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Igrejinha');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Ijuí');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Ilópolis');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Imbé');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Imigrante');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Independência');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Inhacorá');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Ipê');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Ipiranga do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Iraí');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Itaara');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Itacurubi');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Itapuca');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Itaqui');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Itati');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Itatiba do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Ivorá');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Ivoti');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Jaboticaba');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Jacuizinho');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Jacutinga');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Jaguarão');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Jaguari');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Jaquirana');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Jari');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Jóia');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Júlio de Castilhos');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Lagoa Bonita do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Lagoa dos Três Cantos');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Lagoa Vermelha');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Lagoão');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Lajeado');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Lajeado do Bugre');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Lavras do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Liberato Salzano');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Lindolfo Collor');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Linha Nova');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Maçambará');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Machadinho');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Mampituba');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Manoel Viana');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Maquiné');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Maratá');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Marau');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Marcelino Ramos');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Mariana Pimentel');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Mariano Moro');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Marques de Souza');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Mata');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Mato Castelhano');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Mato Leitão');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Mato Queimado');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Maximiliano de Almeida');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Minas do Leão');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Miraguaí');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Montauri');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Monte Alegre dos Campos');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Monte Belo do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Montenegro');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Mormaço');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Morrinhos do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Morro Redondo');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Morro Reuter');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Mostardas');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Muçum');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Muitos Capões');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Muliterno');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Não-Me-Toque');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Nicolau Vergueiro');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Nonoai');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Nova Alvorada');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Nova Araçá');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Nova Bassano');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Nova Boa Vista');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Nova Bréscia');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Nova Candelária');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Nova Esperança do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Nova Hartz');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Nova Pádua');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Nova Palma');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Nova Petrópolis');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Nova Prata');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Nova Ramada');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Nova Roma do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Nova Santa Rita');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Novo Barreiro');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Novo Cabrais');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Novo Hamburgo');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Novo Machado');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Novo Tiradentes');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Novo Xingu');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Osório');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Paim Filho');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Palmares do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Palmeira das Missões');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Palmitinho');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Panambi');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Pantano Grande');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Paraí');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Paraíso do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Pareci Novo');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Parobé');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Passa Sete');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Passo do Sobrado');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Passo Fundo');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Paulo Bento');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Paverama');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Pedras Altas');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Pedro Osório');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Pejuçara');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Pelotas');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Picada Café');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Pinhal');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Pinhal da Serra');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Pinhal Grande');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Pinheirinho do Vale');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Pinheiro Machado');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Pirapó');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Piratini');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Planalto');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Poço das Antas');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Pontão');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Ponte Preta');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Portão');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Porto Alegre');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Porto Lucena');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Porto Mauá');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Porto Vera Cruz');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Porto Xavier');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Pouso Novo');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Presidente Lucena');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Progresso');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Protásio Alves');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Putinga');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Quaraí');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Quatro Irmãos');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Quevedos');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Quinze de Novembro');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Redentora');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Relvado');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Restinga Seca');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Rio dos Índios');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Rio Grande');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Rio Pardo');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Riozinho');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Roca Sales');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Rodeio Bonito');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Rolador');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Rolante');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Ronda Alta');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Rondinha');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Roque Gonzales');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Rosário do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Sagrada Família');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Saldanha Marinho');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Salto do Jacuí');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Salvador das Missões');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Salvador do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Sananduva');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Santa Bárbara do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Santa Cecília do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Santa Clara do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Santa Cruz do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Santa Margarida do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Santa Maria');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Santa Maria do Herval');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Santa Rosa');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Santa Tereza');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Santa Vitória do Palmar');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Santana da Boa Vista');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'SantAna do Livramento');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Santiago');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Santo Ângelo');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Santo Antônio da Patrulha');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Santo Antônio das Missões');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Santo Antônio do Palma');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Santo Antônio do Planalto');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Santo Augusto');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Santo Cristo');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Santo Expedito do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'São Borja');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'São Domingos do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'São Francisco de Assis');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'São Francisco de Paula');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'São Gabriel');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'São Jerônimo');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'São João da Urtiga');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'São João do Polêsine');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'São Jorge');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'São José das Missões');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'São José do Herval');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'São José do Hortêncio');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'São José do Inhacorá');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'São José do Norte');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'São José do Ouro');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'São José do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'São José dos Ausentes');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'São Leopoldo');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'São Lourenço do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'São Luiz Gonzaga');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'São Marcos');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'São Martinho');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'São Martinho da Serra');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'São Miguel das Missões');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'São Nicolau');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'São Paulo das Missões');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'São Pedro da Serra');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'São Pedro das Missões');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'São Pedro do Butiá');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'São Pedro do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'São Sebastião do Caí');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'São Sepé');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'São Valentim');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'São Valentim do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'São Valério do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'São Vendelino');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'São Vicente do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Sapiranga');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Sapucaia do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Sarandi');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Seberi');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Sede Nova');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Segredo');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Selbach');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Senador Salgado Filho');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Sentinela do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Serafina Corrêa');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Sério');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Sertão');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Sertão Santana');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Sete de Setembro');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Severiano de Almeida');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Silveira Martins');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Sinimbu');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Sobradinho');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Soledade');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Tabaí');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Tapejara');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Tapera');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Tapes');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Taquara');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Taquari');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Taquaruçu do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Tavares');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Tenente Portela');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Terra de Areia');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Teutônia');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Tio Hugo');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Tiradentes do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Toropi');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Torres');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Tramandaí');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Travesseiro');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Três Arroios');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Três Cachoeiras');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Três Coroas');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Três de Maio');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Três Forquilhas');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Três Palmeiras');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Três Passos');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Trindade do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Triunfo');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Tucunduva');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Tunas');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Tupanci do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Tupanciretã');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Tupandi');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Tuparendi');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Turuçu');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Ubiretama');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'União da Serra');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Unistalda');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Uruguaiana');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Vacaria');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Vale do Sol');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Vale Real');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Vale Verde');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Vanini');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Venâncio Aires');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Vera Cruz');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Veranópolis');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Vespasiano Correa');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Viadutos');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Viamão');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Vicente Dutra');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Victor Graeff');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Vila Flores');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Vila Lângaro');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Vila Maria');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Vila Nova do Sul');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Vista Alegre');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Vista Alegre do Prata');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Vista Gaúcha');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Vitória das Missões');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Westfalia');
INSERT INTO mydb.cidade (idEstado, nome) VALUES (3,'Xangri-lá');

